# Form implementation generated from reading ui file 'd:\Rei Codes\Hariku-App\others\splashsceen-luis\SplashScreen.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(438, 281)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.dropShadowFrame.setFont(font)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(240, 240, 217);\n"
"    color:rgb(0, 0, 0);\n"
"    border-radius: 25px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dropShadowFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_pic = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_pic.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pic.sizePolicy().hasHeightForWidth())
        self.label_pic.setSizePolicy(sizePolicy)
        self.label_pic.setMaximumSize(QtCore.QSize(50, 50))
        self.label_pic.setText("")
        self.label_pic.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_pic.setPixmap(QtGui.QPixmap("d:\\Rei Codes\\Hariku-App\\others\\splashsceen-luis\\../../assets/Hariku-logo.png"))
        self.label_pic.setScaledContents(True)
        self.label_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_pic.setObjectName("label_pic")
        self.verticalLayout_2.addWidget(self.label_pic, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_desc = QtWidgets.QLabel(self.dropShadowFrame)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        self.label_desc.setFont(font)
        self.label_desc.setStyleSheet("")
        self.label_desc.setObjectName("label_desc")
        self.verticalLayout_2.addWidget(self.label_desc)
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    \n"
"    background-color: rgb(227, 227, 206);\n"
"    color:rgb(0,0,0);\n"
"    border-style: none;\n"
"    boder-color:rgb(40, 186, 130);\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.545, x2:1, y2:0.557, stop:0 rgba(24, 88, 191, 255), stop:1 rgba(40, 186, 130, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.label_loading = QtWidgets.QLabel(self.dropShadowFrame)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(7)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("")
        self.label_loading.setObjectName("label_loading")
        self.verticalLayout_2.addWidget(self.label_loading)
        self.verticalLayout.addWidget(self.dropShadowFrame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.label_desc.setText(_translate("SplashScreen", "<center> Loading <Strong> Apps</Strong> </center>"))
        self.label_loading.setText(_translate("SplashScreen", "<center><Strong> loading .</Strong></center>"))
